### 问题描述

洗牌后的每个元素随机出现在每个位置,且<font color='red'>概率相同</font>

In [1]:
import random
import numpy as np

In [2]:
def test_shuffle(func, numbers=10, count=10000):
    """
    洗牌测试
    :param func: 洗牌函数
    :param numbers: 牌元素的个数
    :param count: 洗牌的次数
    :return:
    """
    result = np.zeros((numbers, numbers))

    for _ in range(count):
        A = [i for i in range(0, numbers)]
        func(A)
        for j in range(numbers):
            result[A[j]][j] += 1  # j号牌被洗到A[j]号牌的次数+1
    print(np.array(result))

In [3]:
def shuffle_system(cards):
    random.shuffle(cards)

* i=0时,任何牌(n张)洗到第0号牌的概率为$1/n$
* i=1时,任何牌(n张)洗到第1号牌的概率也为$1/n$
    * 0号牌: $ \frac{n-1}{n} * \frac{1}{n-1} = \frac{1}{n} $
    * 其他号牌: $ \frac{n-1}{n} * \frac{1}{n-1} = \frac{1}{n} $

* ......

故概率都为$\frac{1}{n}$

In [4]:
def shuffle_correct(cards):
    for i in range(len(cards)):
        randomi = random.randint(i, (len(cards) - 1))
        cards[i], cards[randomi] = cards[randomi], cards[i]

In [5]:
test_shuffle(shuffle_system, 10)  # 概率基本相同

[[ 960. 1015.  951. 1055.  979. 1029. 1017. 1001. 1019.  974.]
 [ 988. 1061. 1028.  996.  956.  998.  986. 1009. 1028.  950.]
 [1046.  957.  987.  985.  968.  974. 1007. 1069.  952. 1055.]
 [ 972. 1004.  956.  999. 1053. 1017. 1002.  987.  981. 1029.]
 [ 985. 1007. 1052. 1032.  990.  975.  975. 1001.  993.  990.]
 [ 990. 1018. 1014.  974.  998.  995.  985. 1023.  983. 1020.]
 [1007. 1017. 1062.  930. 1045.  933. 1003.  981.  994. 1028.]
 [1041. 1018. 1019.  995.  994.  991. 1008. 1005.  948.  981.]
 [1008.  942.  987. 1006.  993. 1040. 1031.  978. 1080.  935.]
 [1003.  961.  944. 1028. 1024. 1048.  986.  946. 1022. 1038.]]


In [6]:
test_shuffle(shuffle_correct, 10)  # 概率基本相同

[[ 962. 1086.  986.  971.  977. 1007.  993.  967. 1056.  995.]
 [1024.  979.  967.  995.  999.  997.  968. 1030. 1039. 1002.]
 [ 987.  970.  993.  987. 1015. 1011. 1026.  983. 1006. 1022.]
 [1049.  987.  974. 1018. 1044.  996.  935. 1051.  959.  987.]
 [1001.  988. 1014. 1021.  951.  941. 1041. 1068.  970. 1005.]
 [ 992. 1023. 1043.  983. 1027. 1001. 1019.  940.  982.  990.]
 [1054. 1030.  982.  994. 1024.  999.  969.  970.  998.  980.]
 [1015.  907. 1001. 1001.  975. 1070. 1000. 1011.  980. 1040.]
 [ 987. 1020. 1031. 1015.  977.  986. 1044.  976.  987.  977.]
 [ 929. 1010. 1009. 1015. 1011.  992. 1005. 1004. 1023. 1002.]]
